# Homework 2: Arrays and Tables

In [9]:
# Don't change this cell; just run it.

import numpy as np
from datascience import *

**Recommended Reading**: 
* [Data Types](https://www.inferentialthinking.com/chapters/04/Data_Types.html) 
* [Sequences](https://www.inferentialthinking.com/chapters/05/Sequences.html)
* [Tables](https://www.inferentialthinking.com/chapters/06/Tables.html)

For all problems that you must write explanations and sentences for, you **must** provide your answer in the designated space. Moreover, throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. 

**Deadline:**

This assignment is due Friday, September 3 at 5:00 PM. Late work will penalized as stated in the syllabus.

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged.

You should start early so that you have time to get help if you're stuck. 

## 1. Creating Arrays


**Question 1.1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. 2
2. the square root of 37
3. -3
4. 7 to the power of 1.2

*Note:* Python lists are different/behave differently than numpy arrays. In STOR 120, we use numpy arrays, so please make an **array**, not a python list if you know how to do so.

<!--
BEGIN QUESTION
name: q1_1
-->

In [10]:
weird_numbers = make_array(2, 37 ** (1/2), -3, 7 ** 1.2)
weird_numbers

array([ 2.        ,  6.08276253, -3.        , 10.33041213])

**Question 1.2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

<!--
BEGIN QUESTION
name: q1_2
-->

In [11]:
book_title_words = make_array('Eats', 'Shoots', 'and Leaves')
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 1.3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

<!--
BEGIN QUESTION
name: q1_3
-->

In [12]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


## 2. Indexing Arrays


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.

*Note:* Please don't use bracket notation when indexing if you know how to (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting.

**Question 2.1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

<!--
BEGIN QUESTION
name: q2_1
-->

In [13]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers.item(2)
third_element

-6

**Question 2.2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table.

<!--
BEGIN QUESTION
name: q2_2
-->

In [14]:
blank_a = "third"
blank_b = "fourth"
blank_c = "0"
blank_d = "3"
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

**Question 2.3.** You will sometimes want to find the *last* element of an array.  Suppose an array has 264 elements.  What is the index of its last element?

<!--
BEGIN QUESTION
name: q2_3
-->

In [15]:
index_of_last_element = 263

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 2.4.** The cell below loads an array called `president_birth_years`. This array has the years of birth for all deceased presidents of the United States. Calling `.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births_2021` table. The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

<!--
BEGIN QUESTION
name: q2_4
-->

In [16]:
president_birth_years = Table.read_table("president_births_2021.csv").column('Birth Year')

most_recent_birth_year = max(president_birth_years)
most_recent_birth_year

1924

**Question 2.5.** Finally, assign `sum_of_birth_years` to the sum of the first, sixteenth, and last birth year in `president_birth_years`.

<!--
BEGIN QUESTION
name: q2_5
-->

In [17]:
sum_of_birth_years = president_birth_years.item(0) + president_birth_years.item(15) + president_birth_years.item(38)
sum_of_birth_years

5464

## 3. Basic Array Arithmetic


**Question 3.1.** Multiply the numbers 37, 3773, 3773773, and -350 by 157. Assign each variable below such that `first_product` is assigned to the result of $37 * 157$, `second_product` is assigned to the result of $3773 * 157$, and so on. 

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
-->

In [18]:
first_product = 37 * 157
second_product = 3773 * 157
third_product = 3773773 * 157
fourth_product = -350 * 157
print(first_product, second_product, third_product, fourth_product)

5809 592361 592482361 -54950


**Question 3.2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

<!--
BEGIN QUESTION
name: q3_2
-->

In [19]:
numbers = make_array(37, 3773, 3773773, -350)
products = numbers * 157
products

array([     5809,    592361, 592482361,    -54950])

**Question 3.3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

<!--
BEGIN QUESTION
name: q3_3
-->

In [20]:
correct_products = numbers * 1577
correct_products

array([     58349,    5950021, 5951240021,    -551950])

**Question 3.4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Make sure to **ROUND** the final result after converting to Celsius to the nearest integer using the `np.round` function.

<!--
BEGIN QUESTION
name: q3_4
-->

In [21]:
max_temperatures = Table.read_table('temperatures.csv').column("Daily Max Temperature")

celsius_max_temperatures = np.round((max_temperatures - 32) * (5/9))
celsius_max_temperatures

array([-4., 31., 32., ..., 17., 23., 16.])

**Question 3.5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units, give your answer in Celsius!** Make sure **NOT** to round your answer for this question!

<!--
BEGIN QUESTION
name: q3_5
-->

In [22]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = celsius_max_temperatures - (np.round((min_temperatures - 32) * (5/9)))
celsius_temperature_ranges

array([ 7., 10., 13., ..., 18., 12., 11.])

## 4. World Population


The cell below loads a table of estimates of the world population for different years, starting in 1950. The estimates come from the [US Census Bureau website](https://www.census.gov/en.html).

In [23]:
world = Table.read_table("world_population.csv").select('Year', 'Population')
world.show(4)

The name `population` is assigned to an array of population estimates.

In [24]:
population = world.column(1)
population

array([2557628654, 2594939877, 2636772306, 2682053389, 2730228104,
       2782098943, 2835299673, 2891349717, 2948137248, 3000716593,
       3043001508, 3083966929, 3140093217, 3209827882, 3281201306,
       3350425793, 3420677923, 3490333715, 3562313822, 3637159050,
       3712697742, 3790326948, 3866568653, 3942096442, 4016608813,
       4089083233, 4160185010, 4232084578, 4304105753, 4379013942,
       4451362735, 4534410125, 4614566561, 4695736743, 4774569391,
       4856462699, 4940571232, 5027200492, 5114557167, 5201440110,
       5288955934, 5371585922, 5456136278, 5538268316, 5618682132,
       5699202985, 5779440593, 5857972543, 5935213248, 6012074922,
       6088571383, 6165219247, 6242016348, 6318590956, 6395699509,
       6473044732, 6551263534, 6629913759, 6709049780, 6788214394,
       6866332358, 6944055583, 7022349283, 7101027895, 7178722893,
       7256490011])

In this question, you will apply some built-in Numpy functions to this array. Numpy is a module that is often used in Data Science!

The difference function `np.diff` subtracts each element in an array from the element after it within the array. As a result, the length of the array `np.diff` returns will always be one less than the length of the input array.

The cumulative sum function `np.cumsum` outputs an array of partial sums. For example, the third element in the output array corresponds to the sum of the first, second, and third elements.

**Question 4.1.** Very often in data science, we are interested understanding how values change with time. Use `np.diff` and `np.max` (or just `max`) to calculate the largest annual change in population between any two consecutive years.

<!--
BEGIN QUESTION
name: q4_1
-->

In [25]:
largest_population_change = max(np.diff(population))
largest_population_change

87515824

**Question 4.2.** What do the values in the resulting array represent (choose one)?

In [26]:
np.cumsum(np.diff(population))

array([  37311223,   79143652,  124424735,  172599450,  224470289,
        277671019,  333721063,  390508594,  443087939,  485372854,
        526338275,  582464563,  652199228,  723572652,  792797139,
        863049269,  932705061, 1004685168, 1079530396, 1155069088,
       1232698294, 1308939999, 1384467788, 1458980159, 1531454579,
       1602556356, 1674455924, 1746477099, 1821385288, 1893734081,
       1976781471, 2056937907, 2138108089, 2216940737, 2298834045,
       2382942578, 2469571838, 2556928513, 2643811456, 2731327280,
       2813957268, 2898507624, 2980639662, 3061053478, 3141574331,
       3221811939, 3300343889, 3377584594, 3454446268, 3530942729,
       3607590593, 3684387694, 3760962302, 3838070855, 3915416078,
       3993634880, 4072285105, 4151421126, 4230585740, 4308703704,
       4386426929, 4464720629, 4543399241, 4621094239, 4698861357])

1) The total population change between consecutive years, starting at 1951.

2) The total population change between 1950 and each later year, starting at 1951.

3) The total population change between 1950 and each later year, starting inclusively at 1950.

<!--
BEGIN QUESTION
name: q4_2
-->

In [27]:
# Assign cumulative_sum_answer to 1, 2, or 3
cumulative_sum_answer = 2

## 5. Old Faithful


Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 5.1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

<!--
BEGIN QUESTION
name: q5_1
-->

In [28]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = min(waiting_times)
longest = max(waiting_times)
average = np.mean(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235294 minutes on average.


**Question 5.2.** Assign `smallest_decrease` to the smallest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. 

*Hint 1*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/05/1/Arrays.html#Functions-on-Arrays). You have also seen this function earlier in the homework!

*Hint 2*: We want to return the absolute value of the smallest decrease.

<!--
BEGIN QUESTION
name: q5_2
-->

In [29]:
smallest_decrease = abs(min(np.diff(waiting_times)))
smallest_decrease

45

**Question 5.3.** If you expected Old Faithful to erupt every 74 minutes, you would expect to wait a total of `74 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the expected and actual total amount of waiting time to see the first `i+1` eruptions. 

*Hint*: You'll need to compare a cumulative sum to a range. You'll go through `np.arange` more thoroughly in a future lab, but you can read about it in this [textbook section](https://www.inferentialthinking.com/chapters/05/2/Ranges.html).

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 74 * 3 = 222. Therefore, `difference_from_expected.item(2)` should be $|207 - 222| = 15$.

<!--
BEGIN QUESTION
name: q5_3
-->

In [30]:
difference_from_expected = abs(np.arange(74, 20202, 74) - np.cumsum(waiting_times))
difference_from_expected

array([  5,  15,  15,  27,  16,  35,  21,  10,  33,  22,  42,  32,  28,
        55,  46,  68,  80,  70,  92,  87, 110, 137, 133, 138, 138, 129,
       148, 146, 142, 137, 138, 135, 143, 137, 137, 159, 185, 179, 194,
       178, 172, 188, 178, 194, 195, 186, 196, 217, 209, 224, 223, 207,
       227, 221, 241, 232, 235, 245, 242, 235, 250, 240, 266, 258, 272,
       254, 250, 246, 255, 256, 248, 266, 261, 264, 276, 274, 288, 284,
       282, 273, 272, 264, 268, 277, 278, 264, 262, 256, 282, 270, 284,
       268, 292, 288, 299, 301, 291, 290, 313, 305, 317, 303, 328, 319,
       312, 339, 329, 351, 339, 332, 331, 346, 331, 326, 341, 334, 358,
       347, 362, 349, 370, 375, 372, 390, 376, 369, 398, 390, 409, 393,
       422, 413, 431, 416, 444, 436, 459, 447, 468, 463, 456, 470, 462,
       459, 457, 472, 466, 491, 469, 490, 487, 484, 493, 486, 489, 493,
       486, 467, 488, 473, 502, 490, 506, 502, 510, 508, 519, 505, 527,
       508, 533, 550, 547, 553, 546, 539, 540, 564, 553, 553, 57

**Question 5.4.** Let’s imagine your guess for the next wait time was always just the length of the previous waiting time. If you always guessed the previous waiting time, how big would your error in guessing the waiting times be, on average?

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

<!--
BEGIN QUESTION
name: q5_4
-->

In [39]:
average_error = sum(abs(np.diff(waiting_times))) / 271
average_error

20.52029520295203

## 6. Tables


**Question 6.1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: `fruit name` and `count`.  Assign the new table to the variable `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

<!--
BEGIN QUESTION
name: q6_1
-->

In [32]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns(
    'fruit name', ('apple', 'orange', 'pineapple'),
    'count', (4, 3, 3)
)
fruits

fruit name | count
apple      | 4
orange     | 3
pineapple  | 3

**Question 6.2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit. Load it as a table named `inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table.

<!--
BEGIN QUESTION
name: q6_2
-->

In [33]:
inventory = Table.read_table('inventory.csv')
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

**Question 6.3.** Does each box at the fruit stand contain a different fruit? Set `all_different` to `True` if each box contains a different fruit or to `False` if multiple boxes contain the same fruit.

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.

<!--
BEGIN QUESTION
name: q6_3
-->

In [34]:
all_different = True
all_different

True

**Question 6.4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`.

<!--
BEGIN QUESTION
name: q6_4
-->

In [35]:
sales = Table.read_table('sales.csv')
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

**Question 6.5.** How many fruits did the store sell in total on that day?

<!--
BEGIN QUESTION
name: q6_5
-->

In [36]:
total_fruits_sold = sum(sales.column('count sold'))
total_fruits_sold

638

**Question 6.6.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

<!--
BEGIN QUESTION
name: q6_6
-->

In [37]:
total_revenue = sum(sales.column('count sold') * sales.column('price per fruit ($)'))
total_revenue

106.85

**Question 6.7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

<!--
BEGIN QUESTION
name: q6_7
-->

In [38]:
remaining_inventory = Table().with_columns(
    'box ID', inventory.column('box ID'),
    'fruit name', inventory.column('fruit name'),
    'count', inventory.column('count') - sales.column('count sold')
)
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23